### ISSUE TITLE
feat: add month number in toJewishDate function

### ISSUE THREAD

**Issue by upsilon01** [Shmulik-Kravitz/jewish-date#1]
it would be nice to have the month number as well as the month name
for example: 
```js
console.log(jewishDate);
 // { year: 5780, month: 4, monthName: "Tevet", day: 4 }
```

**Comment by Shmulik-Kravitz** [comment]
Hi @upsilon01,

The month number exists in version 1.0.3, will fix the example in the readme.md

Thank you and have a good day
Shmulik
