### ISSUE TITLE
jewish date is one day behind

### ISSUE THREAD

**Issue by sysimgrp** [Shmulik-Kravitz/jewish-date#13]

**Comment by rashidul-hasan** [comment]
Hi, I'm having the same issue. how did you fix this? Thanks.

**Comment by sysimgrp** [comment]
In my case, I found that it was caused by the formatting of the parameter to the date() function in node.js.  'mm/dd/yyyy' works but 'yyyy-dd-mm' returns the previous Jewish date.

const testdate = new Date('5/9/2023');  // automatically assumes 4 hours from midnight - yields the correct Jewish date
//const testdate = new Date('2023-05-09');  //  yields previous jewish date
const jewishDate = toJewishDate(testdate);
console.log(testdate);
console.log(jewishDate); // { year: 5783, monthName: "Iyyar", month: 8, day: 18 }
