### ISSUE TITLE
Incorrect value

### ISSUE THREAD

**Issue by yringler** [Shmulik-Kravitz/jewish-date#16]
I'm seeing
`toGregorianDate({day: 1, monthName: 'Kislev', year: 5784})`
return [Mon Nov 13 2023](https://www.chabad.org/calendar/view/day.asp?tdate=11/13/2023), which is not correct; it's actually nov 14

**Comment by Shmulik-Kravitz** [comment]
Hi,

Are you using the latest version?

**Comment by yringler** [comment]
Yes. [Here's a JS fiddle.](https://jsfiddle.net/z9wjneg6/5/)
Good ol' off by one errors. Everyone's favorite

**Comment by yringler** [comment]
Using it via jewish-dates-core [here](https://github.com/yringler/my-schedule-x-demo/blob/try-jewish-dates-core/src/dates-core-impl.ts), to get the weeks in the month, starting from sunday (even if sunday is the month before)

**Comment by Shmulik-Kravitz** [comment]
> Yes. [Here's a JS fiddle.](https://jsfiddle.net/z9wjneg6/5/) Good ol' off by one errors. Everyone's favorite
I followed the link and it looks ok "Tue Nov 14 2023 00:00:00 GMT+0200 (Israel Standard Time)"
![image](https://github.com/user-attachments/assets/4c9d8b96-5765-4a3f-b8d0-6757473eb705)

**Comment by Shmulik-Kravitz** [comment]
> Using it via jewish-dates-core [here](https://github.com/yringler/my-schedule-x-demo/blob/try-jewish-dates-core/src/dates-core-impl.ts), to get the weeks in the month, starting from sunday (even if sunday is the month before)

Can you please send a JSFiddle?

**Comment by yringler** [comment]
NM, I don't think that's actually relevant here

**Comment by yringler** [comment]
> > Yes. [Here's a JS fiddle.](https://jsfiddle.net/z9wjneg6/5/) Good ol' off by one errors. Everyone's favorite
> > I followed the link and it looks ok "Tue Nov 14 2023 00:00:00 GMT+0200 (Israel Standard Time)"

Wow!
Yes, confirmed that it works when I set my system time to Israel time.

But in EST it shows Monday.

-- Edit: updated jsfiddle to convert date to jewish date. Also not working in EST. Also many unit tests fail in EST
